import {
  FolderKanban,
  FolderOpen,
  Calendar,
  FileText,
  Search,
  Users,
  Briefcase,
  Settings,
  Plus,
  Command,
  X,
  ChevronRight,
  ChevronLeft,
  MoreVertical,
  Bug,
  Mail,
  ArrowLeft,
  Check,
  Receipt,
  PlayCircle,
  StopCircle,
} from 'lucide-react';

export const Icons = {
  Projects: FolderKanban,
  FolderOpen: FolderOpen,
  Today: Calendar,
  Notes: FileText,
  FileText: FileText,
  Search: Search,
  Team: Users,
  Clients: Briefcase,
  Settings: Settings,
  Plus: Plus,
  Command: Command,
  Close: X,
  ChevronRight: ChevronRight,
  ChevronLeft: ChevronLeft,
  MoreVertical: MoreVertical,
  Bug: Bug,
  Mail: Mail,
  ArrowLeft: ArrowLeft,
  Check: Check,
  Invoices: Receipt,
  PlayCircle: PlayCircle,
  StopCircle: StopCircle,
};

